### ISSUE TITLE
Regarding the output of "tao.var_v1_array" and "tao.var" interface commands

### ISSUE THREAD

**Issue by weiyuanlou** [bmad-sim/pytao#55]
The output of `tao.var_v1_array(var_name)` is a huge list of all the values which requires additional parsing on the user end. A dictionary is preferred.

The output of `tao.var(var_name)` is a list of some (index?) values which does not include the variable value. Is this intended?

My example code below requires $LCLS_LATTICE, but I'm sure the same thing happens with other lattices with pre-defined variables.

`from pytao import Tao

tao = Tao(f'-init $LCLS_LATTICE/bmad/models/sc_hxr/tao.init -noplot')

tao.var_v1_array('q.L1')

tao.var('q.L1[1]')`

**Comment by ChristopherMayes** [comment]
#56 adds special parsing of `tao.var_v1_array`

**Comment by DavidSagan** [comment]
I assume this issue is solved and will close it.
