### ISSUE TITLE
Calculation of 2nd order Taylor terms affected by including markers

### ISSUE THREAD

**Issue by weiyuanlou** [bmad-sim/pytao#66]
Hi Dave, attached lattice is a short line with few sbends, quads, and sextuples.
You can do `sho Taylor -order 2` to see the tt.xxx terms.
However if you insert markers ( by un-commenting the 2nd last line in lat.bmad ) , then these terms differ.
For instance, the t566 term changes from -1.61 m to -1.60 m.

Is this supposed to happen with PTC calculation? Thanks.

[lat.zip](https://github.com/bmad-sim/pytao/files/11472787/lat.zip)

**Comment by DavidSagan** [comment]
@weiyuanlou I don't normally look at the pytao issue forum so I did not see this until now. Please open an issue on bmad-ecosystem and I will take a look.
