### ISSUE TITLE
Add ability to filter certain error messages

### ISSUE THREAD

**Issue by ken-lauer** [bmad-sim/pytao#85]
Raising `RuntimeError` for certain errors is undesirable, depending on what the user is trying to do. This seems to be a recurring theme based on what I've heard and recently reported issues (#84) 

If `pytao` could filter user-defined message classes such as these and redirect them to the logging system, maybe that would be a good solution? (cc @ChristopherMayes )

For example:
```
[ERROR | 2024-JUL-12 15:57:24] tao_set_invalid:
    UNSTABLE ORBIT AT EVALUATION POINT
    FOR DATUM: abc.x[4] with data_type: bpm_orbit.x
```

Not sure how it would look, but perhaps some simple string match like this could be fine:
`tao.ignore_error("tao_set_invalid", "UNSTABLE ORBIT")`

**Comment by ChristopherMayes** [comment]
Yes, there are a few like this that aren't quite "errors" to me.

@DavidSagan what do you consider an "error" vs "warning"?

**Comment by DavidSagan** [comment]
Essentially, an error occurs when "unexpectedly" the computation cannot be done. The problem is that where you draw the line is somewhat arbitrary.

**Comment by DavidSagan** [comment]
About 1800 lines give or take. But something someone with only a little training could do. I think better would be to enable the User to opt out using the routine name generating the error which is already something that PyTao knows about.

**Comment by DavidSagan** [comment]
Another thought is to add more error levels for finer control.
